In [2]:
library(org.Rn.eg.db)#这个是属于注释包，每个基因集可能对应的注释包不一样
library(org.Dr.eg.db)
library(org.Mm.eg.db)#
library("clusterProfiler")
library(biomaRt)
library(tidyverse)
library(limma)
library(IOBR)
library(fgsea)
library(Seurat)
library(Seurat)
library(ggplot2)
library(dplyr)
library(stringr)
library(DESeq2)
library("FactoMineR")
library(ggplot2)
library(vegan)
library(ape)
library(phyloseq)
library(ggalt)
library(microeco)
#library(jsd)
library("factoextra")
library(Seurat)
library(stringr)
library(ggplot2)
library(pheatmap)
library(dplyr)
library("spatstat.geom")
library(Seurat)
library(Rcpp)
library(harmony)
library(stringr)
library(dplyr)
library(patchwork)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(scales)
library(ggsignif)
library(corrplot)
library(edgeR)
library(ggplot2)
library(FactoMineR)   # PCA分析软件包
library(factoextra)   # PCA分析软件包
library(corrplot)     # 绘制相关性图形
library(pheatmap)
library(tidyverse)
library(clusterProfiler)  # GO和KEGG富集分析
library(org.Hs.eg.db)     # 人类注释数据库
library(GSEABase)    # GESA富集分析
library(ggplot2)     # 可视化绘图
library(tidyverse)   # 数据处理和整理
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(cowplot)
library(monocle)
library(tidyverse)
library(reshape2)
####GO
#载入ggplot2包；
library(ggplot2)
#install.packages("ggpubr")
#载入ggpubr包；
library(ggpubr)
library(GO.db)
library(org.Hs.eg.db)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
library(ggnewscale)
library(org.Mm.eg.db)
library(dplyr)
library(stringr)
library(ComplexUpset)
options(warn=-1)####忽略警告
######upset
library(readxl)
library(msigdbr)
###GO kegg
library(EnhancedVolcano)
library(Seurat)
library(patchwork)
library(dplyr)
library(glue)
library(future)
library(ggplot2)
library(cowplot)
options(future.globals.maxSize = 30 * 1024^3)
library(stringr)
library(pheatmap)
library(RColorBrewer)
library(ggpubr)
library(viridis)
library(ggrepel)
library(reshape2)
library(tidyr)
library(clusterProfiler)
library(GSVA)

In [5]:
library(msigdbr)

In [7]:
####gs
######GO KEGG
####let us find something
####GSVA genesets
genesets <- msigdbr(species = "Homo sapiens", category = "C5")#msigdbr导入基因集
genesets <- subset(genesets, select = c("gs_name","gene_symbol")) %>% as.data.frame()#as data.frame
genesets$gs_name <- str_replace(genesets$gs_name,"GOBP_","")
head(genesets)
genesets$gs_name <- gsub("_", " ", genesets$gs_name)
genesets$gs_name <- tolower(substring(genesets$gs_name, 1))
# genesets <- split(genesets$gene_symbol, genesets$gs_name)#
head(genesets)

  gs_name                                     gene_symbol
1 10_FORMYLTETRAHYDROFOLATE_METABOLIC_PROCESS AASDHPPT
2 10_FORMYLTETRAHYDROFOLATE_METABOLIC_PROCESS ALDH1L1
3 10_FORMYLTETRAHYDROFOLATE_METABOLIC_PROCESS ALDH1L2
4 10_FORMYLTETRAHYDROFOLATE_METABOLIC_PROCESS MTHFD1
5 10_FORMYLTETRAHYDROFOLATE_METABOLIC_PROCESS MTHFD1L
6 10_FORMYLTETRAHYDROFOLATE_METABOLIC_PROCESS MTHFD2L

  gs_name                                     gene_symbol
1 10 formyltetrahydrofolate metabolic process AASDHPPT
2 10 formyltetrahydrofolate metabolic process ALDH1L1
3 10 formyltetrahydrofolate metabolic process ALDH1L2
4 10 formyltetrahydrofolate metabolic process MTHFD1
5 10 formyltetrahydrofolate metabolic process MTHFD1L
6 10 formyltetrahydrofolate metabolic process MTHFD2L

In [8]:
genesets1 <- msigdbr(species = "Homo sapiens", category = "C2")#msigdbr导入基因集
genesets1 <- subset(genesets1, select = c("gs_name","gene_symbol")) %>% as.data.frame()#as data.frame
genesets1$gs_name <- str_replace(genesets1$gs_name,"KEGG_","")
head(genesets1)
genesets1$gs_name <- gsub("_", " ", genesets1$gs_name)
genesets1$gs_name <- tolower(substring(genesets1$gs_name, 1))
# genesets <- split(genesets$gene_symbol, genesets$gs_name)#
genesets1$gs_name <- paste0("C2 ",genesets1$gs_name)
head(genesets1)

  gs_name                  gene_symbol
1 ABBUD_LIF_SIGNALING_1_DN AHNAK
2 ABBUD_LIF_SIGNALING_1_DN ALCAM
3 ABBUD_LIF_SIGNALING_1_DN ANKRD40
4 ABBUD_LIF_SIGNALING_1_DN ARID1A
5 ABBUD_LIF_SIGNALING_1_DN BCKDHB
6 ABBUD_LIF_SIGNALING_1_DN C16orf89

  gs_name                     gene_symbol
1 C2 abbud lif signaling 1 dn AHNAK
2 C2 abbud lif signaling 1 dn ALCAM
3 C2 abbud lif signaling 1 dn ANKRD40
4 C2 abbud lif signaling 1 dn ARID1A
5 C2 abbud lif signaling 1 dn BCKDHB
6 C2 abbud lif signaling 1 dn C16orf89

In [17]:
grep("lycerophospholipid",unique(genesets$gs_name),value = TRUE)

[1] "glycerophospholipid biosynthetic process"
[2] "glycerophospholipid catabolic process"
[3] "glycerophospholipid metabolic process"
[4] "gomf glycerophospholipid flippase activity"

In [ ]:
Ceramide Signaling Pathway

In [18]:
gss <- c("sphingosine biosynthetic process",'glycerophospholipid biosynthetic process','glycerophospholipid catabolic process','glycerophospholipid metabolic process')

In [19]:
m <- subset(genesets,subset=gs_name%in%gss)
write.csv(m,"ggs_ud.csv")